### PR TITLE
Update neomodel to 4.0.3

### PR DESCRIPTION
**Pull request by mprahl**
Now that the following PR has been released,
neomodel can be updated to the latest release:
https://github.com/neo4j-contrib/neomodel/pull/553

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
The pined version used in docker-compose should also be changed. It would be a good idea to define the version in one place and reuse it in the CI and in the prod environments.

**Review by apaplaus — APPROVED** [review]

**Comment by mprahl** [comment]
@lioramilbaum could you please point me to the place where you say needs updating?

To your other point, it is defined in one place which is in `setup.py`. All the other requirements.txt files get the version from this.

**Comment by lioramilbaum** [comment]
> @lioramilbaum could you please point me to the place where you say needs updating?
> 
> To your other point, it is defined in one place which is in `setup.py`. All the other requirements.txt files get the version from this.

docker-compose.yml

**Comment by mprahl** [comment]
@lioramilbaum I don't see neomodel (Python library for interacting with Neo4j) referenced there. Could you please point to the specific line?

**Comment by lioramilbaum** [comment]
> @lioramilbaum I don't see neomodel (Python library for interacting with Neo4j) referenced there. Could you please point to the specific line?

My bad. For some reason I thought the change impacts neo4j release.

**Review by lioramilbaum — APPROVED** [review]

**Pull request merged**
